import { detailedDescription, dialogue } from './speech.js';
// Pure rendering helpers; JSON content is always escaped before becoming HTML.
export const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const object = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
export function parseProject(input) {
  const root = typeof input === 'string' ? JSON.parse(input.replace(/^\uFEFF/, '')) : input;
  if (!object(root)) throw new Error('项目必须是 JSON 对象。');
  const project = root.project ?? root;
  if (!object(project) || typeof project.direction_name !== 'string' || !Array.isArray(project.characters) || !Array.isArray(project.storyboard)) throw new Error('项目需要 direction_name、characters 和 storyboard 字段。');
  if (!project.characters.every(object) || !project.storyboard.every((segment) => object(segment) && Array.isArray(segment.mvinfo) && segment.mvinfo.every(object))) throw new Error('人物或分镜结构无效。');
  return { root, project, settings: object(root.generation_settings) ? root.generation_settings : {}, version: root.schema_version ?? 'legacy' };
}
export const shotsOf = (project) => project.storyboard.flatMap((segment, index) => segment.mvinfo.map((shot, shotIndex) => ({ ...shot, segment, segmentIndex: index, shotIndex })));
export function mediaUrl(value, type) {
  const source = typeof value === 'string' ? value : value?.data_url ?? value?.dataUrl ?? value?.url;
  if (typeof source !== 'string') return '';
  if (type === 'image' && /^data:image\/(png|jpeg|jpg|webp|gif|avif);base64,[a-z0-9+/=\s]+$/i.test(source)) return source;
  if ((type === 'audio' || type === 'video') && new RegExp(`^data:${type}/[a-z0-9.+-]+(?:;[a-z0-9=.-]+)*;base64,[a-z0-9+/=\\s]+$`, 'i').test(source)) return source;
  // Relative /uploads paths and local server URLs are not portable cloud assets.
  try { const url = new URL(source); return url.protocol === 'https:' ? url.href : ''; } catch { return ''; }
}
export function media(value, type, label) {
  const source = mediaUrl(value, type);
  if (!source) return `<div class="${type === 'image' || type === 'video' ? 'media-empty' : 'rounded-lg bg-gray-100 px-4 py-4 text-xs text-gray-400'}">${esc(label)} · ${value ? '素材地址不可用，请使用 HTTPS 或内嵌素材' : '暂无素材'}</div>`;
  if (type === 'image') return `<a href="${esc(source)}" target="_blank" rel="noopener noreferrer"><img src="${esc(source)}" alt="${esc(label)}" loading="lazy" class="aspect-video w-full rounded-lg bg-gray-100 object-contain" data-media></a>`;
  return `<${type} controls preload="none" src="${esc(source)}" aria-label="${esc(label)}" class="w-full rounded-lg ${type === 'video' ? 'aspect-video bg-gray-100' : ''}" data-media></${type}>`;
}
export function detail(label, value, open = false) {
  if (value == null || value === '') return '';
  return `<details class="detail" ${open ? 'open' : ''}><summary class="font-medium">${esc(label)}</summary><pre>${esc(typeof value === 'object' ? JSON.stringify(value, null, 2) : value)}</pre></details>`;
}
const readButton = (key, text, label = '播放朗读') => `<button type="button" class="secondary my-3 text-accent" data-read="${esc(key)}" data-label="${esc(label)}" aria-pressed="false" ${text?.trim() ? '' : 'disabled'}>${esc(text?.trim() ? label : '暂无可朗读文字')}</button>`;
const info = (label, value) => value == null || value === '' ? '' : `<div><dt class="text-xs text-gray-400">${esc(label)}</dt><dd class="mt-2 break-words text-sm leading-6">${esc(value)}</dd></div>`;
const sectionTitle = (title, subtitle = '') => `<div class="mb-7"><h2 class="text-xl font-semibold">${esc(title)}</h2>${subtitle ? `<p class="mt-2 muted">${esc(subtitle)}</p>` : ''}</div>`;
export function overview(project, settings) {
  const director = project.director_plan ?? {}, basics = project.basics ?? {};
  return `<div class="fade-in grid gap-12 lg:grid-cols-[1.5fr_1fr]"><section>${sectionTitle('创作方案')}<dl class="grid grid-cols-2 gap-7">${info('内容形式', director.content_form)}${info('画面比例', director.aspect_ratio)}${info('图片工作流', settings.image_workflow)}${info('视频工作流', settings.video_workflow)}${info('统一风格', director.style_name)}${info('制作模式', director.audio_plan?.production_style)}</dl><div class="mt-8">${detail('叙事策略', director.narrative_strategy, true)}${detail('拍摄方式', basics.shooting_method)}${detail('艺术风格', basics.art_style_description)}${detail('视觉风格锁', director.visual_style_lock)}${detail('源文覆盖', director.source_coverage_note)}${detail('生成设置', settings)}</div></section><section>${sectionTitle('场景与环境')}${(basics.environment_anchors ?? []).map((anchor) => `<div class="border-b border-gray-200 pb-5 mb-5"><p class="eyebrow">${esc(anchor.id)}</p><p class="mt-2 muted">${esc(anchor.description)}</p></div>`).join('') || '<p class="muted">暂无环境设定。</p>'}</section></div>`;
}
const optionalMedia = (value, type, label) => mediaUrl(value, type) ? media(value, type, label) : '';
const editableText = (label, value, path, context, rows = 8) => {
  const id = `edit-${path.replaceAll('.', '-')}`;
  return `<div class="editor-block"><div class="editor-heading"><label for="${esc(id)}" class="text-sm font-semibold">${esc(label)}</label><button type="button" class="copy-button" data-copy="${esc(id)}" aria-label="${esc(context)}：拷贝${esc(label)}">拷贝</button></div><textarea id="${esc(id)}" class="prompt-editor" data-edit="${esc(path)}" rows="${rows}" spellcheck="false" aria-label="${esc(context)}：${esc(label)}">${esc(value)}</textarea></div>`;
};
export function characters(project) {
  return `<div class="fade-in">${sectionTitle('人物展示', `${project.characters.length} 位人物 · 人物设定 / 图像提示词`)}${project.characters.map((character, index) => `<article class="border-b border-gray-200 pb-9 mb-9"><p class="eyebrow">CHARACTER ${String(index + 1).padStart(2, '0')}</p><div class="flex flex-wrap items-baseline gap-3 mt-2"><h3 class="text-2xl font-semibold">${esc(character.name)}</h3><p class="muted">${esc(character.role)}</p></div>${editableText('人物设定 / 图像提示词', character.description, `characters.${index}.description`, character.name, 10)}${readButton(`character-${index}`, character.description, '▶ 朗读人物设定')}<details class="detail"><summary class="font-medium">其他人物信息</summary><div class="mt-4"><p class="text-sm text-gray-500">${esc((character.traits ?? []).join(' / '))}</p>${detail('参考板布局', character.reference_sheet?.layout)}${detail('Z-Image 提示词', character.reference_sheet?.z_image_prompt)}${detail('Krea 提示词', character.reference_sheet?.krea_prompt)}${detail('音色设定', character.voice_profile?.instruct)}${optionalMedia(character.generated_assets?.image, 'image', `${character.name} 人物参考板`)}${optionalMedia(character.generated_assets?.video, 'video', `${character.name} 人物视频`)}</div></details></article>`).join('') || '<p class="muted">项目没有人物。</p>'}</div>`;
}
function voiceBlock(name, voice, key) {
  return `<article class="border-b border-gray-200 pb-6 mb-6"><div class="flex flex-wrap items-baseline gap-3"><h3 class="text-lg font-semibold">${esc(name)}</h3><span class="text-xs text-gray-400">${esc(voice.voice_id)} · ${esc(voice.language)}</span></div><p class="mt-3 muted">${esc(voice.instruct)}</p><blockquote class="my-4 border-l-2 border-accent pl-4 text-sm leading-7">${esc(voice.reference_text)}</blockquote>${readButton(key, dialogue(voice.reference_text), '▶ 朗读台词')}${media(voice.preview_audio || voice.reference_audio, 'audio', `${name} 固定音色`)}${detail('音色参数', { generation_mode: voice.generation_mode, speaker_label: voice.speaker_label, seed: voice.seed, reference_language: voice.reference_language, status: voice.status })}</article>`;
}
export function audio(project) {
  const plan = project.director_plan?.audio_plan ?? {}, shots = shotsOf(project);
  return `<div class="fade-in"><section>${sectionTitle('逐镜头声音', `${shots.length} 个镜头 · 台词`)}<div class="dialogue-list">${shots.map((shot) => `<article class="mb-8 border-b border-gray-200 pb-7"><div class="flex flex-wrap items-baseline gap-3"><h3 class="text-lg font-semibold">${esc(shot.shot_id || '镜头')}</h3><span class="font-mono text-xs text-gray-400">${esc(shot.timestamp)}</span></div><p class="mt-2 text-xs text-gray-500">${esc((shot.audio_plan?.speakers ?? []).map((speaker) => `${speaker.character_name} (${speaker.voice_id ?? speaker.speaker_label ?? ''})`).join(' / '))}</p>${editableText('台词', shot.audio_plan?.audio_text ?? shot.lyrics, `storyboard.${shot.segmentIndex}.mvinfo.${shot.shotIndex}.dialogue`, shot.shot_id, 3)}${readButton(`dialogue-${shot.segmentIndex}-${shot.shotIndex}`, dialogue(shot.audio_plan?.audio_text ?? shot.lyrics), '▶ 朗读台词')}<div class="space-y-3">${optionalMedia(shot.generated_assets?.voice_audio ?? shot.generated_assets?.audio, 'audio', '配音')}${optionalMedia(shot.generated_assets?.music_audio, 'audio', '镜头配乐')}${optionalMedia(shot.generated_assets?.drive_audio, 'audio', 'Drive Audio')}</div></article>`).join('') || '<p class="muted">暂无镜头台词。</p>'}</div></section><details class="detail mt-10"><summary class="font-medium">固定音色与音乐章节</summary><div class="mt-8"><div class="grid gap-12 lg:grid-cols-2"><section>${sectionTitle('固定音色', '旁白与人物音色参考')}${plan.narrator_voice ? voiceBlock('旁白', plan.narrator_voice, 'voice-narrator') : ''}${project.characters.map((character, index) => character.voice_profile ? voiceBlock(character.name, character.voice_profile, `voice-character-${index}`) : '').join('')}</section><section>${sectionTitle('音乐章节', `${(plan.chapters ?? []).length} 个章节`)}${(plan.chapters ?? []).map((chapter, index) => `<article class="mb-8 border-b border-gray-200 pb-6"><p class="eyebrow">${esc(chapter.chapter_id)} · ${esc(chapter.target_duration_seconds)}s</p><h3 class="mt-2 text-xl font-semibold">${esc(chapter.title)}</h3><p class="mt-2 text-xs text-gray-400">${esc(chapter.music_workflow)} · ${esc(chapter.generation_mode)} · ${esc(chapter.bpm)} BPM</p><p class="my-4 muted">${esc(chapter.caption)}</p>${readButton(`chapter-${index}`, chapter.generation_mode === 'vocal' ? dialogue(chapter.lyrics) : '', '▶ 朗读歌词')}${media(chapter.generated_audio, 'audio', '章节配乐')}${detail('结构与歌词', chapter.lyrics)}${detail('标签与参数', { tags: chapter.tags, key_scale: chapter.key_scale, time_signature: chapter.time_signature, language: chapter.language, shot_refs: chapter.shot_refs })}</article>`).join('') || '<p class="muted">暂无音乐章节。</p>'}</section></div></div></details></div>`;
}
export function storyboard(project, { search = '', segment = '', mode = '' } = {}) {
  const matches = shotsOf(project).filter((shot) => (!segment || String(shot.segmentIndex) === segment) && (!mode || shot.generation_plan?.mode === mode) && (!search || JSON.stringify({ ...shot, segment: undefined }).toLowerCase().includes(search.toLowerCase())));
  let previousSegment = -1;
  return `<div class="fade-in">${sectionTitle('分镜展示', `${matches.length} / ${shotsOf(project).length} 个镜头`)}${matches.map((shot) => {
    const heading = previousSegment === shot.segmentIndex ? '' : `<div class="mb-6 border-l-2 border-accent pl-4"><p class="eyebrow">SEGMENT ${esc(shot.segment.segment_id)} · ${esc(shot.segment.movielength)}</p><p class="mt-2 text-sm leading-7">${esc(shot.segment.content_narrative)}</p>${detail('段落提示词', shot.segment.prompts)}</div>`;
    previousSegment = shot.segmentIndex;
    const assets = shot.generated_assets ?? {};
    return `${heading}<article class="mb-9 border-b border-gray-200 pb-9"><div class="flex flex-wrap items-center justify-between gap-3"><h3 class="text-lg font-semibold">${esc(shot.shot_id || '镜头')}</h3><span class="font-mono text-xs text-gray-400">${esc(shot.timestamp)}</span></div>${editableText('视频提示词', shot.video_prompt, `storyboard.${shot.segmentIndex}.mvinfo.${shot.shotIndex}.video_prompt`, shot.shot_id, 14)}${readButton(`shot-${shot.segmentIndex}-${shot.shotIndex}`, detailedDescription(shot.video_prompt), '▶ 朗读详细描述')}<details class="detail"><summary class="font-medium">其他镜头信息</summary><div class="mt-4"><p class="text-xs text-gray-400">${esc(shot.generation_plan?.mode ?? shot.type)} · ${esc(shot.generation_plan?.duration_seconds ?? shot.audio_plan?.duration_seconds ?? '')}s</p>${detail('台词', shot.audio_plan?.audio_text ?? shot.lyrics)}${detail('画面文字', shot.on_screen_text)}${detail('源文', shot.source_text)}${detail('首帧提示词', shot.image_prompt)}${detail('目标尾帧提示词', shot.last_frame_image_prompt)}${detail('镜头声音计划', shot.audio_plan)}${detail('生成计划与参考人物', shot.generation_plan)}<div class="space-y-4">${optionalMedia(assets.video, 'video', `${shot.shot_id} 视频`)}${optionalMedia(assets.image, 'image', `${shot.shot_id} 首帧`)}${optionalMedia(assets.target_last_frame, 'image', '目标尾帧')}${optionalMedia(assets.last_frame, 'image', '实际尾帧')}${optionalMedia(assets.drive_audio, 'audio', 'Drive Audio')}</div></div></details></article>`;
  }).join('') || '<p class="muted py-10">没有符合条件的镜头。</p>'}</div>`;
}
